version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      app_network:
        ipv4_address: 172.20.0.2
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16