version: '3'
services:
  app:
    container_name: laravel_blade_starter
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - "8101:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # env_file:
    #   - .env