version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./:/var/www/html
      - composer_cache:/root/.composer/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8111:80
    env_file:
      - .env
    networks:
      - docker-app

volumes:
  composer_cache:

networks:
  docker-app:
    name: docker-app
    driver: bridge