version: '3'
services:
  app:
    container_name: laravel_blade_starter
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    network_mode: bridge
    ports:
      - "8101:80"
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # env_file:
    #   - .env

volumes:
  vendor_data:
  node_modules_data: